site_name: fastapi-project-post Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "hadenlabs/fastapi-project-post"
repo_url: "https://github.com/hadenlabs/fastapi-project-post"
copyright: 'Copyright © 2021 <a href="https://github.com/hadenlabs">hadenlabs</a>'

google_analytics:
  - ""
  - "auto"
